[build]
  command = "npm run build"
  publish = "out"

[build.environment]
  NODE_VERSION = "18"
  NPM_VERSION = "9"

# API Routes
[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200

# Multi-language redirects
[[redirects]]
  from = "/"
  to = "/en"
  status = 302
  force = false
  conditions = {Language = ["en"]}

[[redirects]]
  from = "/"
  to = "/zh"
  status = 302
  force = false
  conditions = {Language = ["zh"]}

[[redirects]]
  from = "/"
  to = "/ja"
  status = 302
  force = false
  conditions = {Language = ["ja"]}

[[redirects]]
  from = "/"
  to = "/ko"
  status = 302
  force = false
  conditions = {Language = ["ko"]}

# SPA fallback for client-side routing
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Security headers
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
    Permissions-Policy = "geolocation=(), microphone=(), camera=()"

# Cache static assets
[[headers]]
  for = "/static/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/_next/static/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

# Function configuration
[functions]
  node_bundler = "esbuild"
  
[functions."crawler"]
  timeout = 30

[functions."markets"]
  timeout = 10

# Environment variables for functions
[context.production.environment]
  NODE_ENV = "production"

[context.deploy-preview.environment]
  NODE_ENV = "development"